// constants/resumeStatus.ts
export enum ResumeStatus {
  SUBMITTED = "SUBMITTED",
  REVIEWED = "REVIEWED",
  SHORTLISTED = "SHORTLISTED",
  ONHOLD = "ONHOLD",
  INTERVIEW_IN_PROCESS = "INTERVIEW_IN_PROCESS",
  INTERVIEWED = "INTERVIEWED",
  SELECTED_IN_FINAL_INTERVIEW = "SELECTED_IN_FINAL_INTERVIEW",
  OFFERED = "OFFERED",
  OFFER_DECLINED = "OFFER_DECLINED",
  HIRED = "HIRED",
  REJECTED = "REJECTED",
  DUPLICATE = "DUPLICATE",
}