import countryData from "country-flag-emoji-json";

// Comprehensive country data with phone codes, flags, and ISO codes
// Data sourced from multiple reliable sources to ensure completeness

export interface CountryData {
  name: string;
  code: string; // ISO 3166-1 alpha-2 country code
  phoneCode: string;
  emoji: string;
  image: string;
  unicode?: string;
}

// Use the country-flag-emoji-json library for comprehensive country data
// This provides all countries with their ISO codes, names, phone codes, and emoji flags
export const COMPLETE_COUNTRY_DATA: CountryData[] = countryData.map(
  (country: any) => ({
    code: country.code,
    name: country.name,
    phoneCode: "+1", // Not needed for country selector
    emoji: country.emoji,
    image: country.image,
    unicode: country.unicode,
  })
);

// Legacy manual data (kept for reference)
const LEGACY_COUNTRY_DATA = [
  // North America
  {
    name: "United States",
    code: "US",
    phoneCode: "+1",
    emoji: "🇺🇸",
    unicode: "U+1F1FA U+1F1F8",
  },
  {
    name: "Canada",
    code: "CA",
    phoneCode: "+1",
    emoji: "🇨🇦",
    unicode: "U+1F1E8 U+1F1E6",
  },
  {
    name: "Mexico",
    code: "MX",
    phoneCode: "+52",
    emoji: "🇲🇽",
    unicode: "U+1F1F2 U+1F1FD",
  },

  // Central America & Caribbean
  {
    name: "Guatemala",
    code: "GT",
    phoneCode: "+502",
    emoji: "🇬🇹",
    unicode: "U+1F1EC U+1F1F9",
  },
  {
    name: "Belize",
    code: "BZ",
    phoneCode: "+501",
    emoji: "🇧🇿",
    unicode: "U+1F1E7 U+1F1FF",
  },
  {
    name: "El Salvador",
    code: "SV",
    phoneCode: "+503",
    emoji: "🇸🇻",
    unicode: "U+1F1F8 U+1F1FB",
  },
  {
    name: "Honduras",
    code: "HN",
    phoneCode: "+504",
    emoji: "🇭🇳",
    unicode: "U+1F1ED U+1F1F3",
  },
  {
    name: "Nicaragua",
    code: "NI",
    phoneCode: "+505",
    emoji: "🇳🇮",
    unicode: "U+1F1F3 U+1F1EE",
  },
  {
    name: "Costa Rica",
    code: "CR",
    phoneCode: "+506",
    emoji: "🇨🇷",
    unicode: "U+1F1E8 U+1F1F7",
  },
  {
    name: "Panama",
    code: "PA",
    phoneCode: "+507",
    emoji: "🇵🇦",
    unicode: "U+1F1F5 U+1F1E6",
  },
  {
    name: "Cuba",
    code: "CU",
    phoneCode: "+53",
    emoji: "🇨🇺",
    unicode: "U+1F1E8 U+1F1FA",
  },
  {
    name: "Jamaica",
    code: "JM",
    phoneCode: "+1876",
    emoji: "🇯🇲",
    unicode: "U+1F1EF U+1F1F2",
  },
  {
    name: "Haiti",
    code: "HT",
    phoneCode: "+509",
    emoji: "🇭🇹",
    unicode: "U+1F1ED U+1F1F9",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    phoneCode: "+1809",
    emoji: "🇩🇴",
    unicode: "U+1F1E9 U+1F1F4",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    phoneCode: "+1787",
    emoji: "🇵🇷",
    unicode: "U+1F1F5 U+1F1F7",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    phoneCode: "+1868",
    emoji: "🇹🇹",
    unicode: "U+1F1F9 U+1F1F9",
  },
  {
    name: "Barbados",
    code: "BB",
    phoneCode: "+1246",
    emoji: "🇧🇧",
    unicode: "U+1F1E7 U+1F1E7",
  },
  {
    name: "Bahamas",
    code: "BS",
    phoneCode: "+1242",
    emoji: "🇧🇸",
    unicode: "U+1F1E7 U+1F1F8",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    phoneCode: "+1268",
    emoji: "🇦🇬",
    unicode: "U+1F1E6 U+1F1EC",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    phoneCode: "+1869",
    emoji: "🇰🇳",
    unicode: "U+1F1F0 U+1F1F3",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    phoneCode: "+1758",
    emoji: "🇱🇨",
    unicode: "U+1F1F1 U+1F1E8",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    phoneCode: "+1784",
    emoji: "🇻🇨",
    unicode: "U+1F1FB U+1F1E8",
  },
  {
    name: "Grenada",
    code: "GD",
    phoneCode: "+1473",
    emoji: "🇬🇩",
    unicode: "U+1F1EC U+1F1E9",
  },
  {
    name: "Dominica",
    code: "DM",
    phoneCode: "+1767",
    emoji: "🇩🇲",
    unicode: "U+1F1E9 U+1F1F2",
  },

  // South America
  {
    name: "Brazil",
    code: "BR",
    phoneCode: "+55",
    emoji: "🇧🇷",
    unicode: "U+1F1E7 U+1F1F7",
  },
  {
    name: "Argentina",
    code: "AR",
    phoneCode: "+54",
    emoji: "🇦🇷",
    unicode: "U+1F1E6 U+1F1F7",
  },
  {
    name: "Chile",
    code: "CL",
    phoneCode: "+56",
    emoji: "🇨🇱",
    unicode: "U+1F1E8 U+1F1F1",
  },
  {
    name: "Colombia",
    code: "CO",
    phoneCode: "+57",
    emoji: "🇨🇴",
    unicode: "U+1F1E8 U+1F1F4",
  },
  {
    name: "Peru",
    code: "PE",
    phoneCode: "+51",
    emoji: "🇵🇪",
    unicode: "U+1F1F5 U+1F1EA",
  },
  {
    name: "Venezuela",
    code: "VE",
    phoneCode: "+58",
    emoji: "🇻🇪",
    unicode: "U+1F1FB U+1F1EA",
  },
  {
    name: "Ecuador",
    code: "EC",
    phoneCode: "+593",
    emoji: "🇪🇨",
    unicode: "U+1F1EA U+1F1E8",
  },
  {
    name: "Bolivia",
    code: "BO",
    phoneCode: "+591",
    emoji: "🇧🇴",
    unicode: "U+1F1E7 U+1F1F4",
  },
  {
    name: "Paraguay",
    code: "PY",
    phoneCode: "+595",
    emoji: "🇵🇾",
    unicode: "U+1F1F5 U+1F1FE",
  },
  {
    name: "Uruguay",
    code: "UY",
    phoneCode: "+598",
    emoji: "🇺🇾",
    unicode: "U+1F1FA U+1F1FE",
  },
  {
    name: "Guyana",
    code: "GY",
    phoneCode: "+592",
    emoji: "🇬🇾",
    unicode: "U+1F1EC U+1F1FE",
  },
  {
    name: "Suriname",
    code: "SR",
    phoneCode: "+597",
    emoji: "🇸🇷",
    unicode: "U+1F1F8 U+1F1F7",
  },
  {
    name: "French Guiana",
    code: "GF",
    phoneCode: "+594",
    emoji: "🇬🇫",
    unicode: "U+1F1EC U+1F1EB",
  },

  // Europe
  {
    name: "United Kingdom",
    code: "GB",
    phoneCode: "+44",
    emoji: "🇬🇧",
    unicode: "U+1F1EC U+1F1E7",
  },
  {
    name: "France",
    code: "FR",
    phoneCode: "+33",
    emoji: "🇫🇷",
    unicode: "U+1F1EB U+1F1F7",
  },
  {
    name: "Germany",
    code: "DE",
    phoneCode: "+49",
    emoji: "🇩🇪",
    unicode: "U+1F1E9 U+1F1EA",
  },
  {
    name: "Italy",
    code: "IT",
    phoneCode: "+39",
    emoji: "🇮🇹",
    unicode: "U+1F1EE U+1F1F9",
  },
  {
    name: "Spain",
    code: "ES",
    phoneCode: "+34",
    emoji: "🇪🇸",
    unicode: "U+1F1EA U+1F1F8",
  },
  {
    name: "Netherlands",
    code: "NL",
    phoneCode: "+31",
    emoji: "🇳🇱",
    unicode: "U+1F1F3 U+1F1F1",
  },
  {
    name: "Belgium",
    code: "BE",
    phoneCode: "+32",
    emoji: "🇧🇪",
    unicode: "U+1F1E7 U+1F1EA",
  },
  {
    name: "Switzerland",
    code: "CH",
    phoneCode: "+41",
    emoji: "🇨🇭",
    unicode: "U+1F1E8 U+1F1ED",
  },
  {
    name: "Austria",
    code: "AT",
    phoneCode: "+43",
    emoji: "🇦🇹",
    unicode: "U+1F1E6 U+1F1F9",
  },
  {
    name: "Sweden",
    code: "SE",
    phoneCode: "+46",
    emoji: "🇸🇪",
    unicode: "U+1F1F8 U+1F1EA",
  },
  {
    name: "Norway",
    code: "NO",
    phoneCode: "+47",
    emoji: "🇳🇴",
    unicode: "U+1F1F3 U+1F1F4",
  },
  {
    name: "Denmark",
    code: "DK",
    phoneCode: "+45",
    emoji: "🇩🇰",
    unicode: "U+1F1E9 U+1F1F0",
  },
  {
    name: "Finland",
    code: "FI",
    phoneCode: "+358",
    emoji: "🇫🇮",
    unicode: "U+1F1EB U+1F1EE",
  },
  {
    name: "Iceland",
    code: "IS",
    phoneCode: "+354",
    emoji: "🇮🇸",
    unicode: "U+1F1EE U+1F1F8",
  },
  {
    name: "Ireland",
    code: "IE",
    phoneCode: "+353",
    emoji: "🇮🇪",
    unicode: "U+1F1EE U+1F1EA",
  },
  {
    name: "Portugal",
    code: "PT",
    phoneCode: "+351",
    emoji: "🇵🇹",
    unicode: "U+1F1F5 U+1F1F9",
  },
  {
    name: "Greece",
    code: "GR",
    phoneCode: "+30",
    emoji: "🇬🇷",
    unicode: "U+1F1EC U+1F1F7",
  },
  {
    name: "Poland",
    code: "PL",
    phoneCode: "+48",
    emoji: "🇵🇱",
    unicode: "U+1F1F5 U+1F1F1",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    phoneCode: "+420",
    emoji: "🇨🇿",
    unicode: "U+1F1E8 U+1F1FF",
  },
  {
    name: "Slovakia",
    code: "SK",
    phoneCode: "+421",
    emoji: "🇸🇰",
    unicode: "U+1F1F8 U+1F1F0",
  },
  {
    name: "Hungary",
    code: "HU",
    phoneCode: "+36",
    emoji: "🇭🇺",
    unicode: "U+1F1ED U+1F1FA",
  },
  {
    name: "Slovenia",
    code: "SI",
    phoneCode: "+386",
    emoji: "🇸🇮",
    unicode: "U+1F1F8 U+1F1EE",
  },
  {
    name: "Croatia",
    code: "HR",
    phoneCode: "+385",
    emoji: "🇭🇷",
    unicode: "U+1F1ED U+1F1F7",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    phoneCode: "+387",
    emoji: "🇧🇦",
    unicode: "U+1F1E7 U+1F1E6",
  },
  {
    name: "Serbia",
    code: "RS",
    phoneCode: "+381",
    emoji: "🇷🇸",
    unicode: "U+1F1F7 U+1F1F8",
  },
  {
    name: "Montenegro",
    code: "ME",
    phoneCode: "+382",
    emoji: "🇲🇪",
    unicode: "U+1F1F2 U+1F1EA",
  },
  {
    name: "North Macedonia",
    code: "MK",
    phoneCode: "+389",
    emoji: "🇲🇰",
    unicode: "U+1F1F2 U+1F1F0",
  },
  {
    name: "Albania",
    code: "AL",
    phoneCode: "+355",
    emoji: "🇦🇱",
    unicode: "U+1F1E6 U+1F1F1",
  },
  {
    name: "Kosovo",
    code: "XK",
    phoneCode: "+383",
    emoji: "🇽🇰",
    unicode: "U+1F1FD U+1F1F0",
  },
  {
    name: "Romania",
    code: "RO",
    phoneCode: "+40",
    emoji: "🇷🇴",
    unicode: "U+1F1F7 U+1F1F4",
  },
  {
    name: "Bulgaria",
    code: "BG",
    phoneCode: "+359",
    emoji: "🇧🇬",
    unicode: "U+1F1E7 U+1F1EC",
  },
  {
    name: "Moldova",
    code: "MD",
    phoneCode: "+373",
    emoji: "🇲🇩",
    unicode: "U+1F1F2 U+1F1E9",
  },
  {
    name: "Ukraine",
    code: "UA",
    phoneCode: "+380",
    emoji: "🇺🇦",
    unicode: "U+1F1FA U+1F1E6",
  },
  {
    name: "Belarus",
    code: "BY",
    phoneCode: "+375",
    emoji: "🇧🇾",
    unicode: "U+1F1E7 U+1F1FE",
  },
  {
    name: "Lithuania",
    code: "LT",
    phoneCode: "+370",
    emoji: "🇱🇹",
    unicode: "U+1F1F1 U+1F1F9",
  },
  {
    name: "Latvia",
    code: "LV",
    phoneCode: "+371",
    emoji: "🇱🇻",
    unicode: "U+1F1F1 U+1F1FB",
  },
  {
    name: "Estonia",
    code: "EE",
    phoneCode: "+372",
    emoji: "🇪🇪",
    unicode: "U+1F1EA U+1F1EA",
  },
  {
    name: "Russia",
    code: "RU",
    phoneCode: "+7",
    emoji: "🇷🇺",
    unicode: "U+1F1F7 U+1F1FA",
  },
  {
    name: "Turkey",
    code: "TR",
    phoneCode: "+90",
    emoji: "🇹🇷",
    unicode: "U+1F1F9 U+1F1F7",
  },
  {
    name: "Cyprus",
    code: "CY",
    phoneCode: "+357",
    emoji: "🇨🇾",
    unicode: "U+1F1E8 U+1F1FE",
  },
  {
    name: "Malta",
    code: "MT",
    phoneCode: "+356",
    emoji: "🇲🇹",
    unicode: "U+1F1F2 U+1F1F9",
  },
  {
    name: "Luxembourg",
    code: "LU",
    phoneCode: "+352",
    emoji: "🇱🇺",
    unicode: "U+1F1F1 U+1F1FA",
  },
  {
    name: "Monaco",
    code: "MC",
    phoneCode: "+377",
    emoji: "🇲🇨",
    unicode: "U+1F1F2 U+1F1E8",
  },
  {
    name: "Andorra",
    code: "AD",
    phoneCode: "+376",
    emoji: "🇦🇩",
    unicode: "U+1F1E6 U+1F1E9",
  },
  {
    name: "San Marino",
    code: "SM",
    phoneCode: "+378",
    emoji: "🇸🇲",
    unicode: "U+1F1F8 U+1F1F2",
  },
  {
    name: "Vatican City",
    code: "VA",
    phoneCode: "+379",
    emoji: "🇻🇦",
    unicode: "U+1F1FB U+1F1E6",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    phoneCode: "+423",
    emoji: "🇱🇮",
    unicode: "U+1F1F1 U+1F1EE",
  },

  // Asia
  {
    name: "China",
    code: "CN",
    phoneCode: "+86",
    emoji: "🇨🇳",
    unicode: "U+1F1E8 U+1F1F3",
  },
  {
    name: "India",
    code: "IN",
    phoneCode: "+91",
    emoji: "🇮🇳",
    unicode: "U+1F1EE U+1F1F3",
  },
  {
    name: "Japan",
    code: "JP",
    phoneCode: "+81",
    emoji: "🇯🇵",
    unicode: "U+1F1EF U+1F1F5",
  },
  {
    name: "South Korea",
    code: "KR",
    phoneCode: "+82",
    emoji: "🇰🇷",
    unicode: "U+1F1F0 U+1F1F7",
  },
  {
    name: "North Korea",
    code: "KP",
    phoneCode: "+850",
    emoji: "🇰🇵",
    unicode: "U+1F1F0 U+1F1F5",
  },
  {
    name: "Indonesia",
    code: "ID",
    phoneCode: "+62",
    emoji: "🇮🇩",
    unicode: "U+1F1EE U+1F1E9",
  },
  {
    name: "Thailand",
    code: "TH",
    phoneCode: "+66",
    emoji: "🇹🇭",
    unicode: "U+1F1F9 U+1F1ED",
  },
  {
    name: "Vietnam",
    code: "VN",
    phoneCode: "+84",
    emoji: "🇻🇳",
    unicode: "U+1F1FB U+1F1F3",
  },
  {
    name: "Philippines",
    code: "PH",
    phoneCode: "+63",
    emoji: "🇵🇭",
    unicode: "U+1F1F5 U+1F1ED",
  },
  {
    name: "Malaysia",
    code: "MY",
    phoneCode: "+60",
    emoji: "🇲🇾",
    unicode: "U+1F1F2 U+1F1FE",
  },
  {
    name: "Singapore",
    code: "SG",
    phoneCode: "+65",
    emoji: "🇸🇬",
    unicode: "U+1F1F8 U+1F1EC",
  },
  {
    name: "Myanmar",
    code: "MM",
    phoneCode: "+95",
    emoji: "🇲🇲",
    unicode: "U+1F1F2 U+1F1F2",
  },
  {
    name: "Cambodia",
    code: "KH",
    phoneCode: "+855",
    emoji: "🇰🇭",
    unicode: "U+1F1F0 U+1F1ED",
  },
  {
    name: "Laos",
    code: "LA",
    phoneCode: "+856",
    emoji: "🇱🇦",
    unicode: "U+1F1F1 U+1F1E6",
  },
  {
    name: "Bangladesh",
    code: "BD",
    phoneCode: "+880",
    emoji: "🇧🇩",
    unicode: "U+1F1E7 U+1F1E9",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    phoneCode: "+94",
    emoji: "🇱🇰",
    unicode: "U+1F1F1 U+1F1F0",
  },
  {
    name: "Nepal",
    code: "NP",
    phoneCode: "+977",
    emoji: "🇳🇵",
    unicode: "U+1F1F3 U+1F1F5",
  },
  {
    name: "Bhutan",
    code: "BT",
    phoneCode: "+975",
    emoji: "🇧🇹",
    unicode: "U+1F1E7 U+1F1F9",
  },
  {
    name: "Maldives",
    code: "MV",
    phoneCode: "+960",
    emoji: "🇲🇻",
    unicode: "U+1F1F2 U+1F1FB",
  },
  {
    name: "Pakistan",
    code: "PK",
    phoneCode: "+92",
    emoji: "🇵🇰",
    unicode: "U+1F1F5 U+1F1F0",
  },
  {
    name: "Afghanistan",
    code: "AF",
    phoneCode: "+93",
    emoji: "🇦🇫",
    unicode: "U+1F1E6 U+1F1EB",
  },
  {
    name: "Iran",
    code: "IR",
    phoneCode: "+98",
    emoji: "🇮🇷",
    unicode: "U+1F1EE U+1F1F7",
  },
  {
    name: "Iraq",
    code: "IQ",
    phoneCode: "+964",
    emoji: "🇮🇶",
    unicode: "U+1F1EE U+1F1F6",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    phoneCode: "+966",
    emoji: "🇸🇦",
    unicode: "U+1F1F8 U+1F1E6",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    phoneCode: "+971",
    emoji: "🇦🇪",
    unicode: "U+1F1E6 U+1F1EA",
  },
  {
    name: "Qatar",
    code: "QA",
    phoneCode: "+974",
    emoji: "🇶🇦",
    unicode: "U+1F1F6 U+1F1E6",
  },
  {
    name: "Kuwait",
    code: "KW",
    phoneCode: "+965",
    emoji: "🇰🇼",
    unicode: "U+1F1F0 U+1F1FC",
  },
  {
    name: "Bahrain",
    code: "BH",
    phoneCode: "+973",
    emoji: "🇧🇭",
    unicode: "U+1F1E7 U+1F1ED",
  },
  {
    name: "Oman",
    code: "OM",
    phoneCode: "+968",
    emoji: "🇴🇲",
    unicode: "U+1F1F4 U+1F1F2",
  },
  {
    name: "Yemen",
    code: "YE",
    phoneCode: "+967",
    emoji: "🇾🇪",
    unicode: "U+1F1FE U+1F1EA",
  },
  {
    name: "Jordan",
    code: "JO",
    phoneCode: "+962",
    emoji: "🇯🇴",
    unicode: "U+1F1EF U+1F1F4",
  },
  {
    name: "Lebanon",
    code: "LB",
    phoneCode: "+961",
    emoji: "🇱🇧",
    unicode: "U+1F1F1 U+1F1E7",
  },
  {
    name: "Syria",
    code: "SY",
    phoneCode: "+963",
    emoji: "🇸🇾",
    unicode: "U+1F1F8 U+1F1FE",
  },
  {
    name: "Israel",
    code: "IL",
    phoneCode: "+972",
    emoji: "🇮🇱",
    unicode: "U+1F1EE U+1F1F1",
  },
  {
    name: "Palestine",
    code: "PS",
    phoneCode: "+970",
    emoji: "🇵🇸",
    unicode: "U+1F1F5 U+1F1F8",
  },
  {
    name: "Armenia",
    code: "AM",
    phoneCode: "+374",
    emoji: "🇦🇲",
    unicode: "U+1F1E6 U+1F1F2",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    phoneCode: "+994",
    emoji: "🇦🇿",
    unicode: "U+1F1E6 U+1F1FF",
  },
  {
    name: "Georgia",
    code: "GE",
    phoneCode: "+995",
    emoji: "🇬🇪",
    unicode: "U+1F1EC U+1F1EA",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    phoneCode: "+7",
    emoji: "🇰🇿",
    unicode: "U+1F1F0 U+1F1FF",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    phoneCode: "+996",
    emoji: "🇰🇬",
    unicode: "U+1F1F0 U+1F1EC",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    phoneCode: "+992",
    emoji: "🇹🇯",
    unicode: "U+1F1F9 U+1F1EF",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    phoneCode: "+993",
    emoji: "🇹🇲",
    unicode: "U+1F1F9 U+1F1F2",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    phoneCode: "+998",
    emoji: "🇺🇿",
    unicode: "U+1F1FA U+1F1FF",
  },
  {
    name: "Mongolia",
    code: "MN",
    phoneCode: "+976",
    emoji: "🇲🇳",
    unicode: "U+1F1F2 U+1F1F3",
  },
  {
    name: "Hong Kong",
    code: "HK",
    phoneCode: "+852",
    emoji: "🇭🇰",
    unicode: "U+1F1ED U+1F1F0",
  },
  {
    name: "Macau",
    code: "MO",
    phoneCode: "+853",
    emoji: "🇲🇴",
    unicode: "U+1F1F2 U+1F1F4",
  },
  {
    name: "Taiwan",
    code: "TW",
    phoneCode: "+886",
    emoji: "🇹🇼",
    unicode: "U+1F1F9 U+1F1FC",
  },
  {
    name: "Brunei",
    code: "BN",
    phoneCode: "+673",
    emoji: "🇧🇳",
    unicode: "U+1F1E7 U+1F1F3",
  },
  {
    name: "East Timor",
    code: "TL",
    phoneCode: "+670",
    emoji: "🇹🇱",
    unicode: "U+1F1F9 U+1F1F1",
  },

  // Africa
  {
    name: "Nigeria",
    code: "NG",
    phoneCode: "+234",
    emoji: "🇳🇬",
    unicode: "U+1F1F3 U+1F1EC",
  },
  {
    name: "Ethiopia",
    code: "ET",
    phoneCode: "+251",
    emoji: "🇪🇹",
    unicode: "U+1F1EA U+1F1F9",
  },
  {
    name: "Egypt",
    code: "EG",
    phoneCode: "+20",
    emoji: "🇪🇬",
    unicode: "U+1F1EA U+1F1EC",
  },
  {
    name: "South Africa",
    code: "ZA",
    phoneCode: "+27",
    emoji: "🇿🇦",
    unicode: "U+1F1FF U+1F1E6",
  },
  {
    name: "Kenya",
    code: "KE",
    phoneCode: "+254",
    emoji: "🇰🇪",
    unicode: "U+1F1F0 U+1F1EA",
  },
  {
    name: "Uganda",
    code: "UG",
    phoneCode: "+256",
    emoji: "🇺🇬",
    unicode: "U+1F1FA U+1F1EC",
  },
  {
    name: "Tanzania",
    code: "TZ",
    phoneCode: "+255",
    emoji: "🇹🇿",
    unicode: "U+1F1F9 U+1F1FF",
  },
  {
    name: "Ghana",
    code: "GH",
    phoneCode: "+233",
    emoji: "🇬🇭",
    unicode: "U+1F1EC U+1F1ED",
  },
  {
    name: "Morocco",
    code: "MA",
    phoneCode: "+212",
    emoji: "🇲🇦",
    unicode: "U+1F1F2 U+1F1E6",
  },
  {
    name: "Algeria",
    code: "DZ",
    phoneCode: "+213",
    emoji: "🇩🇿",
    unicode: "U+1F1E9 U+1F1FF",
  },
  {
    name: "Tunisia",
    code: "TN",
    phoneCode: "+216",
    emoji: "🇹🇳",
    unicode: "U+1F1F9 U+1F1F3",
  },
  {
    name: "Libya",
    code: "LY",
    phoneCode: "+218",
    emoji: "🇱🇾",
    unicode: "U+1F1F1 U+1F1FE",
  },
  {
    name: "Sudan",
    code: "SD",
    phoneCode: "+249",
    emoji: "🇸🇩",
    unicode: "U+1F1F8 U+1F1E9",
  },
  {
    name: "South Sudan",
    code: "SS",
    phoneCode: "+211",
    emoji: "🇸🇸",
    unicode: "U+1F1F8 U+1F1F8",
  },
  {
    name: "Chad",
    code: "TD",
    phoneCode: "+235",
    emoji: "🇹🇩",
    unicode: "U+1F1F9 U+1F1E9",
  },
  {
    name: "Niger",
    code: "NE",
    phoneCode: "+227",
    emoji: "🇳🇪",
    unicode: "U+1F1F3 U+1F1EA",
  },
  {
    name: "Mali",
    code: "ML",
    phoneCode: "+223",
    emoji: "🇲🇱",
    unicode: "U+1F1F2 U+1F1F1",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    phoneCode: "+226",
    emoji: "🇧🇫",
    unicode: "U+1F1E7 U+1F1EB",
  },
  {
    name: "Senegal",
    code: "SN",
    phoneCode: "+221",
    emoji: "🇸🇳",
    unicode: "U+1F1F8 U+1F1F3",
  },
  {
    name: "Mauritania",
    code: "MR",
    phoneCode: "+222",
    emoji: "🇲🇷",
    unicode: "U+1F1F2 U+1F1F7",
  },
  {
    name: "Gambia",
    code: "GM",
    phoneCode: "+220",
    emoji: "🇬🇲",
    unicode: "U+1F1EC U+1F1F2",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    phoneCode: "+245",
    emoji: "🇬🇼",
    unicode: "U+1F1EC U+1F1FC",
  },
  {
    name: "Guinea",
    code: "GN",
    phoneCode: "+224",
    emoji: "🇬🇳",
    unicode: "U+1F1EC U+1F1F3",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    phoneCode: "+232",
    emoji: "🇸🇱",
    unicode: "U+1F1F8 U+1F1F1",
  },
  {
    name: "Liberia",
    code: "LR",
    phoneCode: "+231",
    emoji: "🇱🇷",
    unicode: "U+1F1F1 U+1F1F7",
  },
  {
    name: "Côte d'Ivoire",
    code: "CI",
    phoneCode: "+225",
    emoji: "🇨🇮",
    unicode: "U+1F1E8 U+1F1EE",
  },
  {
    name: "Togo",
    code: "TG",
    phoneCode: "+228",
    emoji: "🇹🇬",
    unicode: "U+1F1F9 U+1F1EC",
  },
  {
    name: "Benin",
    code: "BJ",
    phoneCode: "+229",
    emoji: "🇧🇯",
    unicode: "U+1F1E7 U+1F1EF",
  },
  {
    name: "Cameroon",
    code: "CM",
    phoneCode: "+237",
    emoji: "🇨🇲",
    unicode: "U+1F1E8 U+1F1F2",
  },
  {
    name: "Central African Republic",
    code: "CF",
    phoneCode: "+236",
    emoji: "🇨🇫",
    unicode: "U+1F1E8 U+1F1EB",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    phoneCode: "+240",
    emoji: "🇬🇶",
    unicode: "U+1F1EC U+1F1F6",
  },
  {
    name: "Gabon",
    code: "GA",
    phoneCode: "+241",
    emoji: "🇬🇦",
    unicode: "U+1F1EC U+1F1E6",
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    phoneCode: "+242",
    emoji: "🇨🇬",
    unicode: "U+1F1E8 U+1F1EC",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    phoneCode: "+243",
    emoji: "🇨🇩",
    unicode: "U+1F1E8 U+1F1E9",
  },
  {
    name: "Angola",
    code: "AO",
    phoneCode: "+244",
    emoji: "🇦🇴",
    unicode: "U+1F1E6 U+1F1F4",
  },
  {
    name: "Zambia",
    code: "ZM",
    phoneCode: "+260",
    emoji: "🇿🇲",
    unicode: "U+1F1FF U+1F1F2",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    phoneCode: "+263",
    emoji: "🇿🇼",
    unicode: "U+1F1FF U+1F1FC",
  },
  {
    name: "Namibia",
    code: "NA",
    phoneCode: "+264",
    emoji: "🇳🇦",
    unicode: "U+1F1F3 U+1F1E6",
  },
  {
    name: "Botswana",
    code: "BW",
    phoneCode: "+267",
    emoji: "🇧🇼",
    unicode: "U+1F1E7 U+1F1FC",
  },
  {
    name: "Lesotho",
    code: "LS",
    phoneCode: "+266",
    emoji: "🇱🇸",
    unicode: "U+1F1F1 U+1F1F8",
  },
  {
    name: "Eswatini",
    code: "SZ",
    phoneCode: "+268",
    emoji: "🇸🇿",
    unicode: "U+1F1F8 U+1F1FF",
  },
  {
    name: "Mozambique",
    code: "MZ",
    phoneCode: "+258",
    emoji: "🇲🇿",
    unicode: "U+1F1F2 U+1F1FF",
  },
  {
    name: "Madagascar",
    code: "MG",
    phoneCode: "+261",
    emoji: "🇲🇬",
    unicode: "U+1F1F2 U+1F1EC",
  },
  {
    name: "Mauritius",
    code: "MU",
    phoneCode: "+230",
    emoji: "🇲🇺",
    unicode: "U+1F1F2 U+1F1FA",
  },
  {
    name: "Seychelles",
    code: "SC",
    phoneCode: "+248",
    emoji: "🇸🇨",
    unicode: "U+1F1F8 U+1F1E8",
  },
  {
    name: "Comoros",
    code: "KM",
    phoneCode: "+269",
    emoji: "🇰🇲",
    unicode: "U+1F1F0 U+1F1F2",
  },
  {
    name: "Cape Verde",
    code: "CV",
    phoneCode: "+238",
    emoji: "🇨🇻",
    unicode: "U+1F1E8 U+1F1FB",
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    phoneCode: "+239",
    emoji: "🇸🇹",
    unicode: "U+1F1F8 U+1F1F9",
  },
  {
    name: "Rwanda",
    code: "RW",
    phoneCode: "+250",
    emoji: "🇷🇼",
    unicode: "U+1F1F7 U+1F1FC",
  },
  {
    name: "Burundi",
    code: "BI",
    phoneCode: "+257",
    emoji: "🇧🇮",
    unicode: "U+1F1E7 U+1F1EE",
  },
  {
    name: "Djibouti",
    code: "DJ",
    phoneCode: "+253",
    emoji: "🇩🇯",
    unicode: "U+1F1E9 U+1F1EF",
  },
  {
    name: "Eritrea",
    code: "ER",
    phoneCode: "+291",
    emoji: "🇪🇷",
    unicode: "U+1F1EA U+1F1F7",
  },
  {
    name: "Somalia",
    code: "SO",
    phoneCode: "+252",
    emoji: "🇸🇴",
    unicode: "U+1F1F8 U+1F1F4",
  },
  {
    name: "Malawi",
    code: "MW",
    phoneCode: "+265",
    emoji: "🇲🇼",
    unicode: "U+1F1F2 U+1F1FC",
  },

  // Oceania
  {
    name: "Australia",
    code: "AU",
    phoneCode: "+61",
    emoji: "🇦🇺",
    unicode: "U+1F1E6 U+1F1FA",
  },
  {
    name: "New Zealand",
    code: "NZ",
    phoneCode: "+64",
    emoji: "🇳🇿",
    unicode: "U+1F1F3 U+1F1FF",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    phoneCode: "+675",
    emoji: "🇵🇬",
    unicode: "U+1F1F5 U+1F1EC",
  },
  {
    name: "Fiji",
    code: "FJ",
    phoneCode: "+679",
    emoji: "🇫🇯",
    unicode: "U+1F1EB U+1F1EF",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    phoneCode: "+677",
    emoji: "🇸🇧",
    unicode: "U+1F1F8 U+1F1E7",
  },
  {
    name: "Vanuatu",
    code: "VU",
    phoneCode: "+678",
    emoji: "🇻🇺",
    unicode: "U+1F1FB U+1F1FA",
  },
  {
    name: "Samoa",
    code: "WS",
    phoneCode: "+685",
    emoji: "🇼🇸",
    unicode: "U+1F1FC U+1F1F8",
  },
  {
    name: "Tonga",
    code: "TO",
    phoneCode: "+676",
    emoji: "🇹🇴",
    unicode: "U+1F1F9 U+1F1F4",
  },
  {
    name: "Kiribati",
    code: "KI",
    phoneCode: "+686",
    emoji: "🇰🇮",
    unicode: "U+1F1F0 U+1F1EE",
  },
  {
    name: "Tuvalu",
    code: "TV",
    phoneCode: "+688",
    emoji: "🇹🇻",
    unicode: "U+1F1F9 U+1F1FB",
  },
  {
    name: "Nauru",
    code: "NR",
    phoneCode: "+674",
    emoji: "🇳🇷",
    unicode: "U+1F1F3 U+1F1F7",
  },
  {
    name: "Palau",
    code: "PW",
    phoneCode: "+680",
    emoji: "🇵🇼",
    unicode: "U+1F1F5 U+1F1FC",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    phoneCode: "+692",
    emoji: "🇲🇭",
    unicode: "U+1F1F2 U+1F1ED",
  },
  {
    name: "Micronesia",
    code: "FM",
    phoneCode: "+691",
    emoji: "🇫🇲",
    unicode: "U+1F1EB U+1F1F2",
  },
];

// Helper function to get country by code
export const getCountryByCode = (code: string): CountryData | undefined => {
  return COMPLETE_COUNTRY_DATA.find((country) => country.code === code);
};

// Helper function to get country by phone code
export const getCountryByPhoneCode = (
  phoneCode: string
): CountryData | undefined => {
  return COMPLETE_COUNTRY_DATA.find(
    (country) => country.phoneCode === phoneCode
  );
};

// Helper function to get all unique phone codes
export const getAllPhoneCodes = (): string[] => {
  return Array.from(
    new Set(COMPLETE_COUNTRY_DATA.map((country) => country.phoneCode))
  ).sort();
};

// Export for backward compatibility with existing phone country codes format
export const PHONE_COUNTRY_CODES = COMPLETE_COUNTRY_DATA.map((country) => ({
  code: country.phoneCode,
  name: country.name,
  flag: country.emoji,
  countryCode: country.code,
}));

// Export for country selector format
export const COUNTRY_OPTIONS = COMPLETE_COUNTRY_DATA.map((country) => ({
  code: country.code,
  name: country.name,
  flag: country.emoji,
  phoneCode: country.phoneCode,
})).sort((a, b) => a.name.localeCompare(b.name));